#!/bin/bash

#############################
####@-------MODULE------@####
#############################

module load bioinfo/PLINK/1.90b7
module load bioinfo/ADMIXTURE/1.3.0

#############################
####@-----PARAMETERS----@####
#############################

input_folder=/work/user/fxricaut/Clarence/Data/Phased_Genotype/
input_file=modern.archaic.merge.biallelicSNPs.phased
output_folder=/work/user/fxricaut/Clarence/
output_file=/work/user/fxricaut/Clarence/AdmixselecRes
Selection=Admixselec.txt


#############################
####@-------SCRIPT------@####
#############################



###Data filtering (pruning, bad genotypes, low frequency)
for chr in {1..22}; do

plink --vcf $input_folder$chr.$input_file.vcf.gz.vcf.gz --make-bed --out $output_folder$input_file.$chr --double-id

plink --bfile $output_folder$input_file.$chr --maf 0.05 --geno 0.05 --hwe 10e-6 --keep /work/user/fxricaut/Clarence/$Selection --make-bed --out $output_folder$input_file.$chr.Correc --double-id

plink --bfile $output_folder$input_file.$chr.Correc --indep-pairwise 500 10 0.2 --out $output_folder$output_file.$chr.Correc

plink --bfile $output_folder$input_file.$chr.Correc --extract $output_folder$output_file.$chr.Correc.prune.in --make-bed --out $output_folder$output_file.chr$chr

done

echo "$output_folder$output_file.chr1
$output_folder$output_file.chr2
$output_folder$output_file.chr3
$output_folder$output_file.chr4
$output_folder$output_file.chr5
$output_folder$output_file.chr6
$output_folder$output_file.chr7
$output_folder$output_file.chr8
$output_folder$output_file.chr9
$output_folder$output_file.chr10
$output_folder$output_file.chr11
$output_folder$output_file.chr12
$output_folder$output_file.chr13
$output_folder$output_file.chr14
$output_folder$output_file.chr15
$output_folder$output_file.chr16
$output_folder$output_file.chr17
$output_folder$output_file.chr18
$output_folder$output_file.chr19
$output_folder$output_file.chr20
$output_folder$output_file.chr21
$output_folder$output_file.chr22
"> $output_folder.Allchr.list

##Combining all chromosomes
plink --bfile $output_folder$output_file.chr1 --merge-list $output_folder.Allchr.list --make-bed --out  $output_folder$output_file.complete

##ADMIXTURE

for component in {2..15}; do

admixture --cv=5 -s 1234 $output_folder$output_file.complete.bed $component | tee $output_folder$output_file.complete.$component.log

done
